name: Update Go Dependencies

on:
  schedule:
    - cron: '0 0 * * 1'  # Запуск каждую неделю в понедельник в 00:00 UTC
  workflow_dispatch:      # Возможность ручного запуска

permissions:
  contents: write        # Явное указание разрешений

jobs:
  update:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu
    
    timeout-minutes: 30     # Добавляем таймаут для предотвращения зависания

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Загружаем всю историю
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true       # Включаем кэширование модулей

      - name: Check go.mod and go.sum exist
        run: |
          if [ ! -f go.mod ]; then
            echo "Error: go.mod file not found"
            exit 1
          fi
          
          if [ ! -f go.sum ]; then
            echo "go.sum file not found, initializing it..."
            go mod tidy
          fi

      - name: Clean Go module cache
        run: |
          go clean -modcache
          go clean -cache

      - name: Update dependencies
        id: update
        run: |
          set -euo pipefail  # Строгий режим для bash
          
          echo "Updating all Go dependencies..."
          max_attempts=3
          attempt=1
          
          while [ $attempt -le $max_attempts ]; do
            if go get -u ./...; then
              echo "Dependencies updated successfully on attempt $attempt"
              break
            else
              if [ $attempt -eq $max_attempts ]; then
                echo "Failed to update dependencies after $max_attempts attempts"
                exit 1
              fi
              echo "Update failed on attempt $attempt, retrying..."
              attempt=$((attempt + 1))
              sleep 5
            fi
          done
          
          go mod tidy
          go mod verify || exit 1
          
          echo "Updated dependencies list:"
          go list -m all

      - name: Check for changes
        id: check
        run: |
          if git status --porcelain | grep -qE "go\.mod|go\.sum|vendor"; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in dependencies"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi

      - name: Create Pull Request
        if: steps.check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(deps): update Go dependencies"
          branch: "update-deps"
          title: "Update Go dependencies"
          body: "Automated dependency update."
          labels: "dependencies"
